# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Macaw
email: macaw@cesar.org.br
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://cesarbr.github.io/macaw/" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

permalink: pretty
exclude: ["node_modules/", "*.gemspec", "*.gem", "Gemfile", "Gemfile.lock", "package.json", "package-lock.json",  "script/", "LICENSE.txt", "lib/", "bin/", "README.md", "Rakefile", ".jekyll-cache/"]

# Enable or disable the site search
search_enabled: true

# Aux links for the upper right navigation
# aux_links:
#   "Just the Docs on GitHub":
#     - "//github.com/pmarsceill/just-the-docs"

# Color scheme currently only supports "dark" or nil (default)
color_scheme: nil

# Google Analytics Tracking (optional)
# e.g, UA-1234567-89
# ga_tracking: UA-2709176-10

sass:
    style: compressed

# Build settings
markdown: kramdown
exclude: ["README.md"]