/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface MButton {
    /**
    * Disable button
    */
    'disabled': boolean;
    /**
    * Method showPrompt
    */
    'myTip': () => Promise<string>;
    /**
    * Button tooltip
    */
    'tooltip': string;
  }
  interface MFooter {
    /**
    * Footer class
    */
    'footerType': string;
  }
}

declare global {


  interface HTMLMButtonElement extends Components.MButton, HTMLStencilElement {}
  var HTMLMButtonElement: {
    prototype: HTMLMButtonElement;
    new (): HTMLMButtonElement;
  };

  interface HTMLMFooterElement extends Components.MFooter, HTMLStencilElement {}
  var HTMLMFooterElement: {
    prototype: HTMLMFooterElement;
    new (): HTMLMFooterElement;
  };
  interface HTMLElementTagNameMap {
    'm-button': HTMLMButtonElement;
    'm-footer': HTMLMFooterElement;
  }
}

declare namespace LocalJSX {
  interface MButton {
    /**
    * Disable button
    */
    'disabled'?: boolean;
    /**
    * Button tooltip
    */
    'tooltip'?: string;
  }
  interface MFooter {
    /**
    * Footer class
    */
    'footerType'?: string;
  }

  interface IntrinsicElements {
    'm-button': MButton;
    'm-footer': MFooter;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'm-button': LocalJSX.MButton & JSXBase.HTMLAttributes<HTMLMButtonElement>;
      'm-footer': LocalJSX.MFooter & JSXBase.HTMLAttributes<HTMLMFooterElement>;
    }
  }
}


